name: Resume ci Build

on:                       #when ever someone push to branch main trigger a build  no need for docker build alos for pull request
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{github.run_number}}
    - name: Build latest
      run: docker build . --file Dockerfile --tag my-image-name